name: EnhancedKick
main: at.yawk.bukkit.enhancedkick.EnhancedKick
version: ${version}
description: Enhanced kicking for players that annoy you
commands:
    ckick:
        description: Crash a player
        usage: /ckick <username>
        permission: enhancedkick.kick
